version: '3.8'

services:
  rov:
    image: csmmaterobotics/rov:latest
    build: 
      context: .
      dockerfile: Dockerfile.rov
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    # For future me when you're trying to set these variables:
    # echo 'export DOCKER_USER="$(id -u):$(id -g)"' >> ~/.bash_profile
    user: ${DOCKER_USER}
    pid: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    volumes:
      - /dev/shm:/dev/shm
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys:/sys:ro
      - /usr/lib/gstreamer-1.0/:/usr/lib/gstreamer-1.0
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so
    restart: "no"

  basestation:
    image: csmmaterobotics/basestation:latest
    build: 
      context: .
      dockerfile: Dockerfile.basestation
    network_mode: host