/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LED_MSG_PB_H_INCLUDED
#define PB_LED_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _LEDMsg {
    int32_t id;
    bool ledOn;
    char text[64];
} LEDMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LEDMsg_init_default                      {0, 0, ""}
#define LEDMsg_init_zero                         {0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define LEDMsg_id_tag                            1
#define LEDMsg_ledOn_tag                         2
#define LEDMsg_text_tag                          3

/* Struct field encoding specification for nanopb */
#define LEDMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, BOOL,     ledOn,             2) \
X(a, STATIC,   SINGULAR, STRING,   text,              3)
#define LEDMsg_CALLBACK NULL
#define LEDMsg_DEFAULT NULL

extern const pb_msgdesc_t LEDMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LEDMsg_fields &LEDMsg_msg

/* Maximum encoded size of messages (where known) */
#define LEDMsg_size                              78
#define LED_MSG_PB_H_MAX_SIZE                    LEDMsg_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
