manipulator_controller:
  ros__parameters:
    wrist_invert: False
    wrist_lower_bound: 0.0
    wrist_upper_bound: 180.0
    wrist_pwm_pin: 8
    wrist_scale: 2.5
    clamp_invert: False
    clamp_lower_bound: 0.0
    clamp_upper_bound: 180.0
    clamp_pwm_pin: 11
    clamp_scale: 1.0