flight_controller:
  ros__parameters:
    Thruster0:
      Position: [-1.0, 0.5, 0.0]
      Forward: [0.0, 0.0, 1.0]
      PWM_Pin: 0
    Thruster1:
      Position: [1.0, 0.5, 0.0]
      Forward: [0.0, 0.0, 1.0]
      PWM_Pin: 1 
    Thruster2:
      Position: [1.0, 0.5, 0.0]
      Forward: [0.707106781, -0.707106781, 0.0]
      PWM_Pin: 2
    Thruster3:
      Position: [-1.0, 0.5, 0.0]
      Forward: [0.707106781, 0.707106781, 0.0]
      PWM_Pin: 3
    Thruster4:
      Position: [-1.0, -0.5, 0.0]
      Forward: [0.707106781, -0.707106781, 0.0]
      PWM_Pin: 4
    Thruster5:
      Position: [1.0, -0.5, 0.0]
      Forward: [0.707106781, 0.707106781, 0.0]
      PWM_Pin: 5
    Thruster6:
      Position: [-1.0, -0.5, 0.0]
      Forward: [0.0, 0.0, 1.0]
      PWM_Pin: 6
    Thruster7:
      Position: [1.0, -0.5, 0.0]
      Forward: [0.0, 0.0, 1.0]
      PWM_Pin: 7
    Use_PCA9685: true
    pos_kp: 1.0
    pos_ki: 1.0
    pos_kd: 1.0
    vel_kp: 1.0
    vel_ki: 1.0
    vel_kd: 1.0